"""Ajoute les cellules des Phases 3-7 au notebook."""
import json

with open("DE2_Project_Notebook_EN.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = [
    # ── PHASE 3: TEXT PIPELINE ──
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Phase 3 : Pipeline Texte — Index Inversé\n",
        "\n",
        "Extraction des messages de commit (PushEvent), tokenisation, normalisation,\n",
        "construction d'un **index inversé**, mesure de latence et comparaison Parquet vs CSV.\n"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 3.1 Extraction du corpus texte (messages de commit)\n",
        "t0_text = time.time()\n",
        "\n",
        "bronze_df = spark.read.parquet(CFG[\"paths\"][\"bronze\"])\n",
        "corpus = bronze_df.filter(F.col(\"type\") == \"PushEvent\") \\\n",
        "    .select(F.explode(\"payload.commits\").alias(\"commit\")) \\\n",
        "    .select(\n",
        "        F.col(\"commit.sha\").alias(\"doc_id\"),\n",
        "        F.col(\"commit.message\").alias(\"text\")\n",
        "    ) \\\n",
        "    .filter(F.col(\"text\").isNotNull()) \\\n",
        "    .filter(F.length(\"text\") > 2)\n",
        "\n",
        "corpus_count = corpus.count()\n",
        "print(f\"Documents dans le corpus : {corpus_count}\")\n",
        "corpus.show(5, truncate=80)\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 3.2 Tokenisation, normalisation, suppression des stop-words\n",
        "stop_words = {\"the\",\"a\",\"an\",\"is\",\"it\",\"to\",\"in\",\"of\",\"and\",\"for\",\"on\",\"at\",\n",
        "              \"by\",\"or\",\"as\",\"be\",\"if\",\"no\",\"do\",\"so\",\"up\",\"we\",\"he\",\"me\",\n",
        "              \"my\",\"am\",\"i\",\"was\",\"that\",\"this\",\"with\",\"from\",\"not\",\"are\",\"but\"}\n",
        "\n",
        "tokens = corpus \\\n",
        "    .withColumn(\"text_clean\", F.regexp_replace(F.lower(\"text\"), r\"[^a-z0-9\\\\s]\", \"\")) \\\n",
        "    .withColumn(\"tokens\", F.split(\"text_clean\", r\"\\\\s+\")) \\\n",
        "    .select(\"doc_id\", F.explode(\"tokens\").alias(\"token\")) \\\n",
        "    .filter(F.length(\"token\") > 1) \\\n",
        "    .filter(~F.col(\"token\").isin(list(stop_words)))\n",
        "\n",
        "print(f\"Tokens apres nettoyage : {tokens.count()}\")\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 3.3 Construction de l'index inverse\n",
        "inverted_index = tokens.groupBy(\"token\") \\\n",
        "    .agg(\n",
        "        F.collect_list(\"doc_id\").alias(\"doc_ids\"),\n",
        "        F.count(\"*\").alias(\"freq\")\n",
        "    ) \\\n",
        "    .orderBy(F.desc(\"freq\"))\n",
        "\n",
        "# Sauvegarder en Parquet\n",
        "os.makedirs(CFG[\"paths\"][\"text\"], exist_ok=True)\n",
        "inverted_index.write.mode(\"overwrite\").parquet(CFG[\"paths\"][\"text\"])\n",
        "print(f\"Termes uniques dans l'index : {inverted_index.count()}\")\n",
        "inverted_index.show(10, truncate=False)\n",
        "\n",
        "# Sauvegarder aussi en CSV pour comparaison d'empreinte\n",
        "csv_path = CFG[\"paths\"][\"text\"] + \"_csv\"\n",
        "inverted_index.withColumn(\"doc_ids\", F.concat_ws(\",\", \"doc_ids\")) \\\n",
        "    .write.mode(\"overwrite\").option(\"header\", \"true\").csv(csv_path)\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 3.4 Mesure de latence de requete (SLO <= 2s)\n",
        "idx = spark.read.parquet(CFG[\"paths\"][\"text\"])\n",
        "idx.cache()\n",
        "idx.count()  # Forcer le cache\n",
        "\n",
        "for term in CFG[\"text\"][\"query_terms\"]:\n",
        "    t0 = time.time()\n",
        "    result = idx.filter(F.col(\"token\") == term).collect()\n",
        "    latency = (time.time() - t0) * 1000\n",
        "    freq = result[0][\"freq\"] if result else 0\n",
        "    print(f\"  '{term}': {latency:.1f} ms (freq={freq})\")\n",
        "    record_metric(\"Text\", f\"query_latency_{term}_ms\", f\"{latency:.1f}\", f\"freq={freq}\")\n",
        "\n",
        "idx.unpersist()\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 3.5 Comparaison empreinte Parquet vs CSV\n",
        "import pathlib\n",
        "\n",
        "def dir_size(path):\n",
        "    return sum(f.stat().st_size for f in pathlib.Path(path).rglob('*') if f.is_file())\n",
        "\n",
        "parquet_size = dir_size(CFG[\"paths\"][\"text\"])\n",
        "csv_size = dir_size(CFG[\"paths\"][\"text\"] + \"_csv\")\n",
        "ratio = (parquet_size / csv_size) * 100\n",
        "\n",
        "print(f\"Parquet : {parquet_size / 1024 / 1024:.2f} MB\")\n",
        "print(f\"CSV     : {csv_size / 1024 / 1024:.2f} MB\")\n",
        "print(f\"Ratio   : {ratio:.1f}% (SLO <= 60%)\")\n",
        "\n",
        "t1_text = time.time()\n",
        "record_metric(\"Text\", \"parquet_size_mb\", f\"{parquet_size/1024/1024:.2f}\", \"\")\n",
        "record_metric(\"Text\", \"csv_size_mb\", f\"{csv_size/1024/1024:.2f}\", \"\")\n",
        "record_metric(\"Text\", \"parquet_vs_csv_pct\", f\"{ratio:.1f}\", f\"SLO<=60%\")\n",
        "record_metric(\"Text\", \"text_pipeline_sec\", f\"{t1_text-t0_text:.2f}\", \"\")\n",
        "print(f\"Pipeline texte termine en {t1_text-t0_text:.2f}s\")\n",
    ]},

    # ── PHASE 4: CLUSTERING ──
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Phase 4 : Charge Itérative — Clustering KMeans\n",
        "\n",
        "**Choix : Clustering** (vs Graph). On prepare des features par repo (nombre d'evenements\n",
        "par type), on lance un sweep KMeans avec differents k, on mesure le score de silhouette.\n"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 4.1 Preparation des features par repo\n",
        "from pyspark.ml.feature import VectorAssembler, StandardScaler\n",
        "from pyspark.ml.clustering import KMeans, BisectingKMeans\n",
        "from pyspark.ml.evaluation import ClusteringEvaluator\n",
        "\n",
        "t0_cluster = time.time()\n",
        "silver_df = spark.read.parquet(CFG[\"paths\"][\"silver\"])\n",
        "\n",
        "# Pivoter : une ligne par repo avec le nombre d'evenements par type\n",
        "repo_features = silver_df.groupBy(\"repo_name\").pivot(\"event_type\").count().fillna(0)\n",
        "feature_cols = [c for c in repo_features.columns if c != \"repo_name\"]\n",
        "\n",
        "assembler = VectorAssembler(inputCols=feature_cols, outputCol=\"raw_features\")\n",
        "scaler = StandardScaler(inputCol=\"raw_features\", outputCol=\"scaled_features\",\n",
        "                        withStd=True, withMean=False)\n",
        "\n",
        "assembled = assembler.transform(repo_features)\n",
        "scaler_model = scaler.fit(assembled)\n",
        "scaled_df = scaler_model.transform(assembled)\n",
        "\n",
        "print(f\"Repos avec features : {scaled_df.count()}\")\n",
        "print(f\"Features : {feature_cols}\")\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 4.2 Sweep KMeans : k = [3, 5, 8, 10]\n",
        "evaluator = ClusteringEvaluator(featuresCol=\"scaled_features\", metricName=\"silhouette\")\n",
        "results = []\n",
        "\n",
        "for k in [3, 5, 8, 10]:\n",
        "    kmeans = KMeans(featuresCol=\"scaled_features\", k=k, seed=42, maxIter=20)\n",
        "    model = kmeans.fit(scaled_df)\n",
        "    preds = model.transform(scaled_df)\n",
        "    silhouette = evaluator.evaluate(preds)\n",
        "    cost = model.summary.trainingCost\n",
        "    results.append({\"k\": k, \"silhouette\": silhouette, \"cost\": cost})\n",
        "    print(f\"  k={k}: silhouette={silhouette:.4f}, cost={cost:.2f}\")\n",
        "    record_metric(\"Clustering\", f\"silhouette_k{k}\", f\"{silhouette:.4f}\", f\"cost={cost:.2f}\")\n",
        "\n",
        "best = max(results, key=lambda x: x[\"silhouette\"])\n",
        "print(f\"\\nMeilleur k={best['k']} avec silhouette={best['silhouette']:.4f} (SLO >= 0.25)\")\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 4.3 Experience de partitionnement avant/apres\n",
        "import time as time_mod\n",
        "\n",
        "# AVANT : sans repartitionnement\n",
        "t0 = time_mod.time()\n",
        "km = KMeans(featuresCol=\"scaled_features\", k=best[\"k\"], seed=42, maxIter=20)\n",
        "km.fit(scaled_df)\n",
        "t_before = time_mod.time() - t0\n",
        "\n",
        "# APRES : avec repartitionnement\n",
        "repartitioned = scaled_df.repartition(8)\n",
        "repartitioned.cache()\n",
        "repartitioned.count()\n",
        "t0 = time_mod.time()\n",
        "km.fit(repartitioned)\n",
        "t_after = time_mod.time() - t0\n",
        "repartitioned.unpersist()\n",
        "\n",
        "print(f\"Avant repartitionnement : {t_before:.2f}s\")\n",
        "print(f\"Apres repartitionnement : {t_after:.2f}s\")\n",
        "record_metric(\"Clustering\", \"kmeans_before_sec\", f\"{t_before:.2f}\", \"sans repartition\")\n",
        "record_metric(\"Clustering\", \"kmeans_after_sec\", f\"{t_after:.2f}\", \"repartition(8)\")\n",
        "\n",
        "t1_cluster = time.time()\n",
        "record_metric(\"Clustering\", \"clustering_pipeline_sec\", f\"{t1_cluster-t0_cluster:.2f}\", \"\")\n",
        "print(f\"Pipeline clustering termine en {t1_cluster-t0_cluster:.2f}s\")\n",
    ]},

    # ── PHASE 5: LLM READINESS ──
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Phase 5 : Preparation LLM (Data Readiness)\n",
        "\n",
        "Preparation d'un dataset curate pour la consommation par un LLM.\n",
        "Filtres qualite, schema structure, documentation (data card).\n"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 5.1 Extraction et curation du dataset LLM\n",
        "t0_llm = time.time()\n",
        "\n",
        "bronze_df = spark.read.parquet(CFG[\"paths\"][\"bronze\"])\n",
        "\n",
        "# Extraire les textes des commits, PR et issues\n",
        "commits_text = bronze_df.filter(F.col(\"type\") == \"PushEvent\") \\\n",
        "    .select(F.explode(\"payload.commits\").alias(\"c\"), F.col(\"repo.name\").alias(\"repo\")) \\\n",
        "    .select(\n",
        "        F.col(\"c.sha\").alias(\"doc_id\"),\n",
        "        F.col(\"c.message\").alias(\"text\"),\n",
        "        F.lit(\"commit_message\").alias(\"text_type\"),\n",
        "        F.col(\"repo\").alias(\"source_repo\")\n",
        "    )\n",
        "\n",
        "pr_text = bronze_df.filter(F.col(\"type\") == \"PullRequestEvent\") \\\n",
        "    .select(\n",
        "        F.col(\"id\").alias(\"doc_id\"),\n",
        "        F.col(\"payload.pull_request.title\").alias(\"text\"),\n",
        "        F.lit(\"pr_title\").alias(\"text_type\"),\n",
        "        F.col(\"repo.name\").alias(\"source_repo\")\n",
        "    )\n",
        "\n",
        "all_text = commits_text.unionByName(pr_text)\n",
        "print(f\"Documents bruts : {all_text.count()}\")\n",
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 5.2 Filtres qualite\n",
        "df_llm = all_text \\\n",
        "    .filter(F.col(\"text\").isNotNull()) \\\n",
        "    .filter(F.length(\"text\") >= 10) \\\n",
        "    .withColumn(\"content_hash\", F.xxhash64(\"text\")) \\\n",
        "    .dropDuplicates([\"content_hash\"]) \\\n",
        "    .withColumn(\"source\", F.lit(\"GitHub Archive - Track B\")) \\\n",
        "    .withColumn(\"version\", F.lit(\"v1.0\")) \\\n",
        "    .withColumn(\"curated_at\", F.current_timestamp()) \\\n",
        "    .select(\"doc_id\", \"text\", \"text_type\", \"source_repo\",\n",
        "            \"content_hash\", \"source\", \"version\", \"curated_at\")\n",
        "\n",
        "os.makedirs(CFG[\"paths\"][\"llm_ready\"], exist_ok=True)\n",
        "df_llm.write.mode(\"overwrite\").parquet(CFG[\"paths\"][\"llm_ready\"])\n",
        "\n",
        "total_before = all_text.count()\n",
        "total_after = df_llm.count()\n",
        "pass_rate = (total_after / total_before) * 100\n",
        "\n",
        "print(f\"Avant filtres  : {total_before}\")\n",
        "print(f\"Apres filtres  : {total_after}\")\n",
        "print(f\"Taux de passage: {pass_rate:.1f}% (SLO >= 80%)\")\n",
        "\n",
        "t1_llm = time.time()\n",
        "record_metric(\"LLM\", \"llm_pass_rate_pct\", f\"{pass_rate:.1f}\", f\"SLO>=80%\")\n",
        "record_metric(\"LLM\", \"llm_records\", str(total_after), \"\")\n",
        "record_metric(\"LLM\", \"llm_pipeline_sec\", f\"{t1_llm-t0_llm:.2f}\", \"\")\n",
        "print(f\"Pipeline LLM termine en {t1_llm-t0_llm:.2f}s\")\n",
        "df_llm.printSchema()\n",
    ]},

    # ── PHASE 6: OPTIMIZATION ──
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Phase 6 : Optimisation Physique\n",
        "\n",
        "Compaction, partitionnement, plans EXPLAIN avant/apres.\n"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 6.1 Plans EXPLAIN et optimisation\n",
        "import pathlib\n",
        "pathlib.Path(CFG[\"paths\"][\"proof\"]).mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "# Plan ETL Silver -> Gold\n",
        "silver_df = spark.read.parquet(CFG[\"paths\"][\"silver\"])\n",
        "gold_query = silver_df.groupBy(\"date\", \"repo_name\", \"event_type\") \\\n",
        "    .agg(F.count(\"event_id\").alias(\"event_count\"))\n",
        "\n",
        "plan_etl = gold_query._jdf.queryExecution().explainString(\"formatted\")\n",
        "with open(os.path.join(CFG[\"paths\"][\"proof\"], \"plan_etl.txt\"), \"w\") as f:\n",
        "    f.write(plan_etl)\n",
        "print(\"Plan ETL sauvegarde.\")\n",
        "\n",
        "# Plan Text Index\n",
        "idx = spark.read.parquet(CFG[\"paths\"][\"text\"])\n",
        "plan_text = idx.filter(F.col(\"token\") == \"fix\")._jdf.queryExecution().explainString(\"formatted\")\n",
        "with open(os.path.join(CFG[\"paths\"][\"proof\"], \"plan_text_query.txt\"), \"w\") as f:\n",
        "    f.write(plan_text)\n",
        "print(\"Plan Text Query sauvegarde.\")\n",
        "\n",
        "# Compaction : recrire Gold avec moins de fichiers\n",
        "gold_df = spark.read.parquet(os.path.join(CFG[\"paths\"][\"gold\"], \"repo_activity\"))\n",
        "n_files_before = len(list(pathlib.Path(os.path.join(CFG[\"paths\"][\"gold\"], \"repo_activity\")).rglob(\"*.parquet\")))\n",
        "gold_df.coalesce(2).write.mode(\"overwrite\").parquet(os.path.join(CFG[\"paths\"][\"gold\"], \"repo_activity\"))\n",
        "n_files_after = len(list(pathlib.Path(os.path.join(CFG[\"paths\"][\"gold\"], \"repo_activity\")).rglob(\"*.parquet\")))\n",
        "\n",
        "print(f\"Compaction Gold : {n_files_before} fichiers -> {n_files_after} fichiers\")\n",
        "record_metric(\"Optimization\", \"gold_files_before\", str(n_files_before), \"\")\n",
        "record_metric(\"Optimization\", \"gold_files_after\", str(n_files_after), \"compaction coalesce(2)\")\n",
        "print(\"Optimisation terminee.\")\n",
    ]},

    # ── PHASE 7: EVIDENCE ──
    {"cell_type": "markdown", "metadata": {}, "source": [
        "## Phase 7 : Preuves et Arret\n",
        "\n",
        "Sauvegarde finale des metriques, verification des SLOs, arret de Spark.\n"
    ]},
    {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
        "# 7.1 Verification des SLOs et resume\n",
        "print(\"=\" * 60)\n",
        "print(\"RESUME DU PIPELINE DE2 — GitHub Archive (Track B)\")\n",
        "print(\"=\" * 60)\n",
        "\n",
        "# Lire les metriques\n",
        "with open(CFG[\"paths\"][\"metrics_log\"], \"r\") as f:\n",
        "    lines = f.readlines()\n",
        "print(f\"\\nMetriques enregistrees : {len(lines)} entrees\")\n",
        "print(f\"Fichier : {CFG['paths']['metrics_log']}\")\n",
        "\n",
        "# Verifier les sorties\n",
        "import pathlib\n",
        "for name, path in CFG[\"paths\"].items():\n",
        "    if name in [\"bronze\", \"silver\", \"gold\", \"streaming\", \"text\", \"llm_ready\"]:\n",
        "        p = pathlib.Path(path)\n",
        "        if p.exists():\n",
        "            size = sum(f.stat().st_size for f in p.rglob('*') if f.is_file())\n",
        "            print(f\"  {name:20s} : {size/1024/1024:.1f} MB\")\n",
        "        else:\n",
        "            print(f\"  {name:20s} : MANQUANT\")\n",
        "\n",
        "print(f\"\\nPreuves dans : {CFG['paths']['proof']}\")\n",
        "for f in pathlib.Path(CFG[\"paths\"][\"proof\"]).iterdir():\n",
        "    print(f\"  {f.name}\")\n",
        "\n",
        "spark.stop()\n",
        "print(\"\\nSpark arrete. Pipeline termine.\")\n",
    ]},
]

nb["cells"].extend(cells)
with open("DE2_Project_Notebook_EN.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Phases 3-7 ajoutees : {len(cells)} cellules inserees.")
